// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class GuestBook
{
    public int GuestId { get; set; }

    public string? EmailAddress { get; set; }

    public string? Comment { get; set; }

    public DateTime? CreatedDate { get; set; }
}